In [6]:
import numpy as np 
a_arr = np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
b_arr = np.array([[7, 5, 3], [0, 7, 5], [0, 0, 7]])
c = b_arr.dot(a_arr) + a_arr.dot(b_arr) 

print(c) 

[[14 24 30]
 [ 0 14 24]
 [ 0  0 14]]


In [9]:
arr = np.array([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])
power= np.dot(arr,arr)
print(power)

[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [11]:
matrix_1 = np.array([[3, 5], [6, -1]])
matrix_2 = np.array([[2, 1], [-3, 2]])
matrix_3 = matrix_1.dot(matrix_2)
print(matrix_3)

[[-9 13]
 [15  4]]
[[ 3  5]
 [ 6 -1]]
[[ 2  1]
 [-3  2]]


In [12]:
arr_a = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
a_det = np.linalg.det(arr_a)
print(format(a_det,'.9g'))

35


In [13]:
aa = np.array([[-2, 3, 1,-1], [3, 2, 1, 4], [1, 2, 3, 4], [0, 2, 3, 3]])
rank = np.linalg.matrix_rank(aa) 
print(rank)

3


In [14]:
a_arr = np.array([[2, 3, 4,1], [1, 2, 3, 4], [3, 4, 1, 2], [4, 1, 2, 3]])
a_det = np.linalg.det(a_arr)
print(format(a_det,'.9g'))

-160


In [15]:
a = np.array([[2, 5, 7], [6, 3, 4], [5, -2, -3]])
a_inv = np.linalg.inv(a) 
print(a_inv)

[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [18]:
a_arr = np.matrix('7 3 -6; 7 9 -9; 2 -4 9') 
b_arr = np.matrix('-1; 5; 28') 
print('a=', a_arr) 
print('b=',b_arr) 
a_inv = np.linalg.inv(a_arr) 
print(a_inv) 
x = a_inv.dot(b_arr) 
print('x=',x)

a= [[ 7  3 -6]
 [ 7  9 -9]
 [ 2 -4  9]]
b= [[-1]
 [ 5]
 [28]]
[[ 0.12931034 -0.00862069  0.07758621]
 [-0.23275862  0.21551724  0.06034483]
 [-0.13218391  0.09770115  0.12068966]]
x= [[2.]
 [3.]
 [4.]]


In [19]:
a = np.matrix('7 3 -6; 7 9 -9; 2 -4 9') 
b = np.matrix('-1; 5; 28') 
def kram(a,b): 
    det_a = np.linalg.det(a) 
    if det_a != 0: 
       a1 = np.matrix(a) 
       a2 = np.matrix(a) 
       a3 = np.matrix(a) 
       a1[:, 0] = b 
       a2[:, 1] = b 
       a3[:, 2] = b 
       x = np.linalg.det(a1)/det_a 
       y =np.linalg.det(a2)/det_a 
       z= np.linalg.det(a3)/det_a 
       print('Solving a system of linear algebraic equations by Cramer*s method') 
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3))  
    else: 
        print('Determinant equals zero, the system has no solutions') 
    return x,y,z 
kram(a,b) 
print('Checking the correctness of the solution\n', np.linalg.solve(a,b).round(3))

Solving a system of linear algebraic equations by Cramer*s method
x= 2.0 y= 3.0 z= 4.0
Checking the correctness of the solution
 [[2.]
 [3.]
 [4.]]


In [27]:
a = np.array(np.random.randint(0,5, size=(3,4)))
average_rows = np.mean(a, axis=1)
minimum = np.min(average_rows)
print(a)
print(average_rows)

print('Найнижче середнє значення:', minimum)

[[0 1 3 0]
 [1 2 2 1]
 [1 1 3 2]]
[1.   1.5  1.75]
Найнижче середнє значення: 1.0
