<a href="https://colab.research.google.com/github/kkalinovska/NumMethofProg/blob/main/%D0%9A%D0%B0%D0%BB%D1%96%D0%BD%D0%BE%D0%B2%D1%81%D1%8C%D0%BA%D0%B0_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.0.2'

1. Створити матрицю 3*3, заповнити її цілими випадковими числами від 1 до 5

In [3]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[1, 2, 3],
       [2, 2, 4],
       [5, 3, 3]])

2. Обчислити визначник матриці

In [4]:
det = np.linalg.det(matrix)
det

np.float64(10.000000000000002)

3. Знайти добуток всіх елементів матриці

In [5]:
product = np.prod(matrix)
product

np.int64(4320)

In [9]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(4320)

4. Знайти суму всіх елементів матриці

In [6]:
sum = np.sum(matrix)
sum

np.int64(25)

5. Обчислити найбільший, найменший елементи

In [7]:
max_element = np.max(matrix)

print("Найбільший елемент матриці:", max_element)

min_element = np.min(matrix)

print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


6. Знайти середнє значення  елементів матриці



In [8]:
mean = np.mean(matrix)

print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 2.7777777777777777


7. Знайти матрицю, що складена з квадратних коренів.

In [10]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.         1.41421356 1.73205081]
 [1.41421356 1.41421356 2.        ]
 [2.23606798 1.73205081 1.73205081]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [11]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор-стовпчик

Сума елементів кожного рядка:
[[ 6]
 [ 8]
 [11]]


9. Створити вектор, що містить 25 елементів.Заповни числами від 0 до 9. Відсортувати числа за спаданням

In [12]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[0 5 3 0 0 0 9 5 8 6 4 4 5 6 1 5 2 2 0 9 6 9 3 7 4]
Вектор після сортування за спаданням:
[9 9 9 8 7 6 6 6 5 5 5 5 4 4 4 3 3 2 2 1 0 0 0 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [13]:
from scipy import stats
#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(0), count=np.int64(5))
Медіана: 4.0
Середнє: 4.12
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10.Обчислити суму, різницю,поелементний добуток,частку

In [16]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 8  7 10  5]
 [ 7  1  5  5]
 [ 3 10  6 10]
 [ 2  2  9  1]]

Матриця 2:
[[ 5  7  8  3]
 [ 9  3  5  6]
 [10  7  4  2]
 [10  9  9  6]]


In [17]:
#Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2

#Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

#Обчислюємо поелементну частку матриць
#Для запобігання ділення на нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)

print("\nПоелементна частка матриць:")
print(matrix_division)




Сума матриць:
[[13 14 18  8]
 [16  4 10 11]
 [13 17 10 12]
 [12 11 18  7]]

Різниця матриць:
[[ 3  0  2  2]
 [-2 -2  0 -1]
 [-7  3  2  8]
 [-8 -7  0 -5]]

Поелементний добуток матриць:
[[40 49 80 15]
 [63  3 25 30]
 [30 70 24 20]
 [20 18 81  6]]

Поелементна частка матриць:
[[1.6        1.         1.25       1.66666667]
 [0.77777778 0.33333333 1.         0.83333333]
 [0.3        1.42857143 1.5        5.        ]
 [0.2        0.22222222 1.         0.16666667]]


Висновок: У ході лабораторної роботи ми закріпили практичні навички роботи з бібліотекою NumPy та SciPy. Ми створювали й обробляли матриці та вектори, виконували базові статистичні обчислення та операції над багатовимірними масивами.